### ISSUE TITLE
Code documentation todo list

### ISSUE THREAD

**Issue by Evert-R** [Amsterdam-Music-Lab/MUSCLE#1428]
#### - actions

- [x] experiment.actions.base_action #1444

- [x] experiment.actions.consent #1445

- [x] experiment.actions.explainer #1430 

- [x] experiment.actions.final #1420

- [x] experiment.actions.form #1446

- [x] experiment.actions.frontend_style #1447

- [x] experiment.actions.html #1423

- [x] experiment.actions.info #1438

- [x] experiment.actions.playback #1448

- [x] experiment.actions.redirect #1422

- [x] experiment.actions.score #1438

- [x] experiment.actions.styles #1450

- [x] experiment.actions.trial #1451 

- [x] experiment.actions.utils #1452

- [x] experiment.actions.wrappers #1453

#### - experiment app

- [x] experiment.models

- [ ] experiment.rules

#### - image app

- [x] #1469

#### - participant app

- [x] #1477

- [x] #1483

#### - question app

- [x] #1485

- [x] #1486

#### - result app

- [x] #1457

#### - section app

- [x] section.models

#### - session app

- [x] session.models

#### - theme app

- [x] #1484
